### ISSUE TITLE
 Cannot start service edm-mysq

### ISSUE THREAD

**Issue by gtunon** [elastest/elastest-toolbox#1]
Hi I'm trying to run the normal image but I get this error
```
ERROR: for edm-mysql  Cannot start service edm-mysql: driver failed programming external connectivity on endpoint elastest_edm-mysql_1 (0081d0160804521878a9667b4b506a7abb6157d93ecd8fe2043d964650af073d): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
Encountered errors while bringing up the project.
```
How can I solve them? 

Thank you

**Comment by micaelgallego** [comment]
The problem is that port 3306 is used in the host. For this reason it is not possible for edm-mysql service to use this port. You can free that port before starting ElasTest or start ElasTest with option "--noports" to avoid port binding. In the last case, you will need to use the etm container port to connect to ElasTest GUI.

**Comment by gtunon** [comment]
My bad I had a mysql process running on that port. 
Thankyou
